from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common import action_chains
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select

import time
import pyautogui

driver = webdriver.Chrome()

driver.implicitly_wait(20)

driver.get("http://the-internet.herokuapp.com/login")
driver.maximize_window()
time.sleep(2)
driver.find_element_by_id("username").send_keys("testing")
time.sleep(2)
driver.find_element_by_id("password").send_keys("test123")
time.sleep(2)
driver.find_element_by_xpath('//*[@id="login"]/button').click()
time.sleep(2)
driver.refresh()
driver.find_element_by_id("username").send_keys("tomsmith")
time.sleep(2)
driver.find_element_by_id("password").send_keys("SuperSecretPassword!")
time.sleep(2)
driver.find_element_by_xpath('//*[@id="login"]/button').click()
time.sleep(3)
driver.find_element_by_xpath('//*[@id="content"]/div/a').click()
driver.stop_client()
time.sleep(2)
driver.get("http://the-internet.herokuapp.com/")
#driver.get("http://demoqa.com/droppable")
time.sleep(2)
driver.find_element_by_xpath('//*[@id="content"]/ul/li[1]/a').click()
time.sleep(3)
driver.find_element_by_link_text("Elemental Selenium").click()
time.sleep(3)
driver.switch_to_window(driver.window_handles[1])
driver.close()
time.sleep(2)
driver.switch_to_window(driver.window_handles[0])
driver.back()
driver.refresh()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="content"]/ul/li[2]/a').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="content"]/div/button').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="elements"]/button').click()
time.sleep(2)
driver.back()
driver.refresh()
time.sleep(2)
driver.find_element_by_partial_link_text("Checkboxes").click()
time.sleep(3)
driver.find_element_by_xpath('//*[@id="checkboxes"]/input[1]').click()
time.sleep(2)
driver.find_element_by_xpath('//*[@id="checkboxes"]/input[1]').click()
driver.back()
driver.refresh()
time.sleep(2)
driver.find_element_by_partial_link_text("Context Menu").click()
time.sleep(2)
frame=driver.find_element_by_xpath('//*[@id="hot-spot"]')
actionChains = ActionChains(driver)
actionChains.context_click(frame).perform()
time.sleep(2)
driver.switch_to.alert.accept()
time.sleep(2)
element = driver.find_element_by_xpath('//*[@id="content"]/div/p[1]')
actionChains = ActionChains(driver)
actionChains.double_click(on_element= element)
actionChains.perform()
time.sleep(2)
time.sleep(2)
driver.refresh()
driver.back()
time.sleep(1)
time.sleep(2)
driver.find_element_by_partial_link_text("Disappearing Elements").click()
time.sleep(2)
ActionChains(driver).move_to_element((driver.find_element_by_link_text("Home"))).perform()
time.sleep(2)
ActionChains(driver).move_to_element((driver.find_element_by_link_text("About"))).perform()
time.sleep(2)
ActionChains(driver).move_to_element((driver.find_element_by_link_text("Contact Us"))).perform()
time.sleep(2)
ActionChains(driver).move_to_element((driver.find_element_by_link_text("Portfolio"))).perform()
driver.refresh()
time.sleep(2)
driver.refresh()
time.sleep(2)
ActionChains(driver).move_to_element((driver.find_element_by_link_text("Gallery"))).perform()
time.sleep(2)
driver.find_element_by_link_text("Gallery").click()
time.sleep(2)
driver.back()
ActionChains(driver).move_to_element((driver.find_element_by_link_text("Portfolio"))).perform()
time.sleep(1)
driver.find_element_by_link_text("Portfolio").click()
time.sleep(2)
driver.back()
time.sleep(2)
ActionChains(driver).move_to_element((driver.find_element_by_link_text("Contact Us"))).perform()
time.sleep(1)
driver.find_element_by_link_text("Contact Us").click()
time.sleep(2)
driver.back()
time.sleep(2)
ActionChains(driver).move_to_element((driver.find_element_by_link_text("About"))).perform()
time.sleep(1)
driver.find_element_by_link_text("About").click()
time.sleep(2)
driver.back()
time.sleep(2)
ActionChains(driver).move_to_element((driver.find_element_by_link_text("Home"))).perform()
time.sleep(1)
driver.find_element_by_link_text("Home").click()
time.sleep(2)
driver.minimize_window()
time.sleep(2)
driver.quit()
#driver.find_element_by_link_text("Drag and Drop").click()
#time.sleep(2)
# frameA = driver.find_element_by_id("draggable")
# frameB = driver.find_element_by_id("droppable")
# action = ActionChains(driver)
# #ActionChains(driver).click_and_hold(frameA).move_to_element(frameB).release(frameB).perform()
# time.sleep(2)

# action.drag_and_drop(frameA, frameB).perform()
# time.sleep(2)
#driver.back()
# driver.find_element_by_link_text("File Download").click()
# driver.find_element_by_link_text("logo.jpg").click()
# time.sleep(2)
# driver.back()

# driver.find_element_by_link_text("File Upload").click()
# driver.refresh()
# driver.find_element_by_id("drag-drop-upload").click()
# # driver.find_element_by_xpath('//*[@id="file-upload"]').click()
# pyautogui.write(r"‪C:\Users\ASUS\Pictures\download.png")
# pyautogui.press("enter")
# driver.find_element_by_xpath('//*[@id="file-submit"]').click()